language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "Ue1IAORdUgm0luz4chv/Hhuk5rMWrvV6hoAESli2eAw5YI+pJ7bGus0dm5bE9/ZyM5Wf9dIxSYAiNh9Gn1Fc1DT9bVXGM3RXcEZU6rWoDIRh4SdVtfEXTDn50BTIrS4QWrTTlPIBIxmgvfIEyHTv3tWCRx9HvaNUOkW33nHns39IEd2bTIdemWoWec85I2Hf2iiBOZ0k5E3GjxxTDeqMy+TanRR16a9pYmuewou6rYHqiG2mt9AMwmDHCtgUzC4fpmPK/ajWLhKYkE9RgvrdHY7Rx/ThataWPzeDhyVC8InDaZ/X8kA1Y2qjNcqHGoy1B4zW8mdsOxj4FFv7LEDWV4Oc2B6a+2Q0akbxRUnexBNZqvuuWydtOs2mub62wCSYX8Ioh9jyrN8UdKUoPnbDh9BLsxalAmN9pvDLt9z9LgaJISx0KzSFV896A38yR1TaaHYqyjzyYAnbnSSZolt8EQ0+kOudAcPfAIT90iDnt7s6jdwjiJxskGWF5gHSxjSaxtRZ0jpQ3Mbv0d49JzuP9Uet3P9y+G9Fqq578hScAgISJjmeXdXMN9mLs6WhZep56c8ECdz2/AfOHU259KEhLOOcRmHfkwiFJyLaazmAg/NcqztsHQ/bG1V+l4H45+K9cSPkGv7lf/z/QT/DsIitOhwmHcqyd3s0JmLvhBVkQLM="
    - secure: "XuvVhHvXQTrEkfjMAce3c76EjNhgZVHQmmvyuaeC2pvkxGSqbTjVd/R08akrKkUBa75smq7BkO0z/VlBO8jXbzbuDu5GF/JeKEqtyc/JBr/Y+JsVZT7J7t4cx/Y+PXLCsFoLOoN2vHiIeU3Zn2ot3U+eeCafuAzjAJkPawHXM9jD60IOJf3PRA/3WZYmrxblK18eoNsEdPneUN0tpHZwFUpZqW5TIkZj/uclU9GA6ldaecjBnawXf3Qu+bn1AfoUtDcArJCGKnXAV+Rk+uW2JAnrdK1jaiVAaBex286An43AUqXUZWAtUZMGmfoReP9zTcl60Zc9+3/CQ2c+r1UO19FOM33maasqhCUztxQvWbmp/kibdVMapD6KgBxGvh/mBfrdXVQgiv2ZzyEWPESczEAqSLHTDb41E5RQwX/FG+BioqAg5t3jAoN0AT5pgPahGBrhqbrM1wkAa3UkYM6tG7ieyHwN8NJMdl2EHw5Xmy/8/xDe+ZOXboHnIw3zeO+q1h999zaTRh2MzXG4Dc47YjQZ1fct2IATtNi9SXqaz3fo281FFi3dIUcCcFDnHj3STlGmnD38FX5M2dC6UPWA3WY1AkSms/YvcoMiqybvtF51r+ytxVPlAWK8AjcGqGBYOLQZlOQzx0Ro2ivs9vPqZZ/3G2MstxlW/g+Zo6hDmVE="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
